-- 0001_baseline: the complete NovoApex schema as a single fresh-start
-- baseline, owned by the Go service (no Prisma history is replayed).
--
-- Column order and enum value order deliberately match the schema the Node
-- service produced: sqlc-generated scans are positional for `SELECT *`.
--
-- Conventions inherited from that schema:
--   * ids are TEXT UUIDs generated by the application;
--   * timestamps are TIMESTAMP(3) WITHOUT TIME ZONE holding UTC wall time
--     (the API pins the session TimeZone to UTC);
--   * updated_at has no default — writers set it explicitly;
--   * money is NUMERIC(14,2).

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- Enums ----------------------------------------------------------------------

CREATE TYPE "ConversationState" AS ENUM ('LEAD', 'BROWSING', 'INVOICING', 'SUPPORT', 'ESCALATED', 'CHECKOUT');
CREATE TYPE "FulfillmentType" AS ENUM ('DELIVERY', 'PICKUP');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'CONFIRMED', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED');

-- Tenancy ----------------------------------------------------------------------

CREATE TABLE businesses (
    id                            TEXT NOT NULL,
    name                          TEXT NOT NULL,
    whatsapp_phone_number_id      TEXT NOT NULL,
    created_at                    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMP(3) NOT NULL,
    currency                      TEXT NOT NULL DEFAULT 'GHS',
    assistant_enabled             BOOLEAN NOT NULL DEFAULT true,
    category                      TEXT,
    confirmation_delay_hours      INTEGER NOT NULL DEFAULT 24,
    location                      TEXT,
    owner_phone                   TEXT NOT NULL,
    paystack_recipient_code       TEXT,
    payment_callback_url          TEXT,
    template_language             TEXT NOT NULL DEFAULT 'en',
    -- Meta-approved WhatsApp template for the new-arrivals digest; NULL skips
    -- the business in the new-arrivals scanner.
    new_arrivals_template_name    TEXT,
    last_new_arrivals_notified_at TIMESTAMP(3),
    CONSTRAINT businesses_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX businesses_owner_phone_key ON businesses (owner_phone);
CREATE UNIQUE INDEX businesses_whatsapp_phone_number_id_key ON businesses (whatsapp_phone_number_id);

-- A physical shop; delivery/pickup are independent flags.
CREATE TABLE business_locations (
    id              TEXT NOT NULL,
    business_id     TEXT NOT NULL,
    name            TEXT NOT NULL,
    address         TEXT NOT NULL,
    shop_number     TEXT,
    landmark        TEXT,
    opening_time    TEXT NOT NULL, -- 24-hour "HH:mm"
    closing_time    TEXT NOT NULL, -- 24-hour "HH:mm"
    offers_delivery BOOLEAN NOT NULL DEFAULT true,
    offers_pickup   BOOLEAN NOT NULL DEFAULT true,
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(3) NOT NULL,
    CONSTRAINT business_locations_pkey PRIMARY KEY (id)
);
CREATE INDEX business_locations_business_id_idx ON business_locations (business_id);

-- CRM --------------------------------------------------------------------------

CREATE TABLE customers (
    id                  TEXT NOT NULL,
    business_id         TEXT NOT NULL,
    phone               TEXT NOT NULL,
    name                TEXT,
    acquisition_channel TEXT,
    first_contact_at    TIMESTAMP(3) NOT NULL,
    last_contact_at     TIMESTAMP(3) NOT NULL,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(3) NOT NULL,
    -- Explicit consent for marketing-template sends (new-arrivals digest).
    marketing_opt_in    BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX customers_business_id_phone_key ON customers (business_id, phone);
-- Cross-tenant phone lookup for payment reconciliation.
CREATE INDEX customers_phone_idx ON customers (phone);

CREATE TABLE customer_profiles (
    id                        TEXT NOT NULL,
    customer_id               TEXT NOT NULL,
    preferences               JSONB NOT NULL DEFAULT '[]',
    delivery_area             TEXT,
    average_order_value       NUMERIC(14,2),
    order_frequency_days      DOUBLE PRECISION,
    last_order_at             TIMESTAMP(3),
    total_orders              INTEGER NOT NULL DEFAULT 0,
    total_spent               NUMERIC(14,2) NOT NULL DEFAULT 0,
    sentiment                 TEXT,
    updated_at                TIMESTAMP(3) NOT NULL,
    last_reengagement_at      TIMESTAMP(3),
    late_payment_count        INTEGER NOT NULL DEFAULT 0,
    preferred_payment_network TEXT,
    CONSTRAINT customer_profiles_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX customer_profiles_customer_id_key ON customer_profiles (customer_id);

CREATE TABLE conversations (
    id                    TEXT NOT NULL,
    business_id           TEXT NOT NULL,
    customer_id           TEXT,
    customer_phone        TEXT NOT NULL,
    state                 "ConversationState" NOT NULL DEFAULT 'LEAD',
    is_escalated_to_human BOOLEAN NOT NULL DEFAULT false,
    language              TEXT NOT NULL DEFAULT 'en',
    escalation_reason     TEXT,
    created_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP(3) NOT NULL,
    CONSTRAINT conversations_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX conversations_business_id_customer_phone_key ON conversations (business_id, customer_phone);
CREATE INDEX conversations_business_id_idx ON conversations (business_id);
CREATE INDEX conversations_customer_id_idx ON conversations (customer_id);
CREATE INDEX conversations_customer_phone_idx ON conversations (customer_phone);

-- Catalog ----------------------------------------------------------------------

CREATE TABLE products (
    id            TEXT NOT NULL,
    business_id   TEXT NOT NULL,
    name          TEXT NOT NULL,
    description   TEXT,
    price         NUMERIC(14,2) NOT NULL,
    stock         INTEGER NOT NULL DEFAULT 0,
    sku           TEXT,
    is_available  BOOLEAN NOT NULL DEFAULT true,
    embedding     vector(768),
    created_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(3) NOT NULL,
    category      TEXT,
    delivery_note TEXT,
    request_count INTEGER NOT NULL DEFAULT 0,
    stock_note    TEXT,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE INDEX products_business_id_idx ON products (business_id);

-- 1–5 images per product; position is dense and unique per product, and the
-- content hash rejects duplicate uploads.
CREATE TABLE product_images (
    id           TEXT NOT NULL,
    product_id   TEXT NOT NULL,
    url          TEXT NOT NULL,
    storage_key  TEXT, -- provider delete key (Cloudinary public_id)
    "position"   INTEGER NOT NULL DEFAULT 0,
    embedding    vector(768),
    created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_hash TEXT, -- sha256 of the uploaded bytes
    CONSTRAINT product_images_pkey PRIMARY KEY (id)
);
CREATE INDEX product_images_product_id_idx ON product_images (product_id);
CREATE UNIQUE INDEX product_images_product_id_position_key ON product_images (product_id, "position");
CREATE UNIQUE INDEX product_images_product_id_content_hash_key ON product_images (product_id, content_hash);
CREATE INDEX product_images_embedding_idx ON product_images USING hnsw (embedding vector_cosine_ops);

CREATE TABLE faqs (
    id          TEXT NOT NULL,
    business_id TEXT NOT NULL,
    question    TEXT NOT NULL,
    answer      TEXT NOT NULL,
    policy_tag  TEXT,
    embedding   vector(768),
    created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(3) NOT NULL,
    CONSTRAINT faqs_pkey PRIMARY KEY (id)
);
CREATE INDEX faqs_business_id_idx ON faqs (business_id);

-- Messaging --------------------------------------------------------------------

CREATE TABLE inbound_messages (
    id                  TEXT NOT NULL,
    whatsapp_message_id TEXT NOT NULL,
    sender_phone        TEXT NOT NULL,
    recipient_phone     TEXT NOT NULL,
    message_type        TEXT NOT NULL,
    text_content        TEXT,
    raw_payload         JSONB NOT NULL,
    "timestamp"         TIMESTAMP(3) NOT NULL,
    business_id         TEXT,
    conversation_id     TEXT,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inbound_messages_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX inbound_messages_whatsapp_message_id_key ON inbound_messages (whatsapp_message_id);
CREATE INDEX inbound_messages_business_id_idx ON inbound_messages (business_id);
CREATE INDEX inbound_messages_conversation_id_idx ON inbound_messages (conversation_id);
CREATE INDEX inbound_messages_sender_phone_idx ON inbound_messages (sender_phone);
CREATE INDEX inbound_messages_timestamp_idx ON inbound_messages ("timestamp");

-- Transactional outbox: rows are persisted 'pending' before the send is
-- enqueued; the outbox sweep re-enqueues stranded rows.
CREATE TABLE outbound_messages (
    id                  TEXT NOT NULL,
    whatsapp_message_id TEXT,
    recipient_phone     TEXT NOT NULL,
    message_type        TEXT NOT NULL,
    text_content        TEXT,
    template_name       TEXT,
    raw_payload         JSONB NOT NULL,
    meta_response       JSONB,
    status              TEXT NOT NULL DEFAULT 'sent',
    business_id         TEXT,
    conversation_id     TEXT,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url           TEXT,
    product_id          TEXT, -- set on product-image sends ("already shown" lookup)
    CONSTRAINT outbound_messages_pkey PRIMARY KEY (id)
);
CREATE INDEX outbound_messages_business_id_idx ON outbound_messages (business_id);
CREATE INDEX outbound_messages_conversation_id_idx ON outbound_messages (conversation_id);
CREATE INDEX outbound_messages_conversation_id_product_id_idx ON outbound_messages (conversation_id, product_id);
CREATE INDEX outbound_messages_recipient_phone_idx ON outbound_messages (recipient_phone);
CREATE INDEX outbound_messages_status_idx ON outbound_messages (status);

CREATE TABLE webhook_events (
    id              TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    processed_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT webhook_events_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX webhook_events_idempotency_key_key ON webhook_events (idempotency_key);

-- Orders & money ---------------------------------------------------------------

CREATE TABLE orders (
    id               TEXT NOT NULL,
    business_id      TEXT NOT NULL,
    customer_id      TEXT NOT NULL,
    conversation_id  TEXT,
    status           "OrderStatus" NOT NULL DEFAULT 'PENDING',
    total_amount     NUMERIC(14,2) NOT NULL,
    currency         TEXT NOT NULL DEFAULT 'GHS',
    created_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(3) NOT NULL,
    idempotency_key  TEXT, -- source WhatsApp message id of the confirming turn
    fulfillment_type "FulfillmentType" NOT NULL DEFAULT 'DELIVERY',
    location_id      TEXT, -- pickup shop, PICKUP orders only
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE INDEX orders_business_id_status_idx ON orders (business_id, status);
CREATE INDEX orders_customer_id_idx ON orders (customer_id);
CREATE UNIQUE INDEX orders_idempotency_key_key ON orders (idempotency_key);
CREATE INDEX orders_location_id_idx ON orders (location_id);
CREATE INDEX orders_status_idx ON orders (status);

CREATE TABLE order_items (
    id           TEXT NOT NULL,
    order_id     TEXT NOT NULL,
    product_id   TEXT NOT NULL,
    product_name TEXT NOT NULL, -- immutable snapshot
    quantity     INTEGER NOT NULL,
    unit_price   NUMERIC(14,2) NOT NULL, -- immutable snapshot
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE payments (
    id                  TEXT NOT NULL,
    business_id         TEXT NOT NULL,
    customer_id         TEXT,
    order_id            TEXT,
    external_reference  TEXT,
    amount              NUMERIC(14,2) NOT NULL,
    currency            TEXT NOT NULL DEFAULT 'GHS',
    provider            TEXT NOT NULL,
    network             TEXT,
    status              "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    paid_at             TIMESTAMP(3),
    reconciled_at       TIMESTAMP(3),
    raw_webhook_payload JSONB,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);
CREATE INDEX payments_business_id_paid_at_idx ON payments (business_id, paid_at);
CREATE INDEX payments_business_id_status_idx ON payments (business_id, status);
CREATE INDEX payments_customer_id_idx ON payments (customer_id);
CREATE UNIQUE INDEX payments_external_reference_key ON payments (external_reference);
CREATE INDEX payments_status_idx ON payments (status);

CREATE TABLE payouts (
    id                   TEXT NOT NULL,
    business_id          TEXT NOT NULL,
    amount               NUMERIC(14,2) NOT NULL,
    currency             TEXT NOT NULL DEFAULT 'GHS',
    status               "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    reference            TEXT,
    paystack_transfer_id TEXT,
    created_at           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(3) NOT NULL,
    CONSTRAINT payouts_pkey PRIMARY KEY (id)
);
CREATE INDEX payouts_business_id_status_idx ON payouts (business_id, status);
CREATE UNIQUE INDEX payouts_reference_key ON payouts (reference);
CREATE INDEX payouts_status_idx ON payouts (status);

-- Durable source of truth for delayed follow-ups; a cron claims due rows
-- (CAS on executed_at) and enqueues them.
CREATE TABLE scheduled_follow_ups (
    id           TEXT NOT NULL,
    order_id     TEXT NOT NULL,
    business_id  TEXT NOT NULL,
    customer_id  TEXT NOT NULL,
    job_type     TEXT NOT NULL,
    scheduled_at TIMESTAMP(3) NOT NULL,
    executed_at  TIMESTAMP(3),
    cancelled_at TIMESTAMP(3),
    created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT scheduled_follow_ups_pkey PRIMARY KEY (id)
);
CREATE INDEX scheduled_follow_ups_order_id_idx ON scheduled_follow_ups (order_id);
CREATE INDEX scheduled_follow_ups_scheduled_at_executed_at_cancelled_at_idx ON scheduled_follow_ups (scheduled_at, executed_at, cancelled_at);

-- Foreign keys -----------------------------------------------------------------

ALTER TABLE business_locations ADD CONSTRAINT business_locations_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE conversations ADD CONSTRAINT conversations_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE conversations ADD CONSTRAINT conversations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE customer_profiles ADD CONSTRAINT customer_profiles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE customers ADD CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE faqs ADD CONSTRAINT faqs_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE inbound_messages ADD CONSTRAINT inbound_messages_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE inbound_messages ADD CONSTRAINT inbound_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE orders ADD CONSTRAINT orders_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE orders ADD CONSTRAINT orders_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE orders ADD CONSTRAINT orders_location_id_fkey FOREIGN KEY (location_id) REFERENCES business_locations (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE outbound_messages ADD CONSTRAINT outbound_messages_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE outbound_messages ADD CONSTRAINT outbound_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE payments ADD CONSTRAINT payments_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE payments ADD CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE payouts ADD CONSTRAINT payouts_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE product_images ADD CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE products ADD CONSTRAINT products_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE scheduled_follow_ups ADD CONSTRAINT scheduled_follow_ups_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses (id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE scheduled_follow_ups ADD CONSTRAINT scheduled_follow_ups_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE CASCADE ON DELETE RESTRICT;
